create table if not exists tb_worker (daily_income numeric(38,2), id bigint generated by default as identity, name varchar(255), primary key (id));

INSERT INTO tb_worker (name, daily_Income) VALUES ('Bob', 200.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Maria', 300.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Alex', 250.0);