spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: hr-worker
              uri: lb://hr-worker
              predicates:
                - Path=/workers/**
            - id: hr-payroll
              uri: lb://hr-payroll
              predicates:
                - Path=/payments/**
            - id: hr-user
              uri: lb://hr-user
              predicates:
                - Path=/users/**
            - id: hr-oauth
              uri: lb://hr-oauth
              predicates:
                - Path=/users/**
              sensitive-headers: Cookie,Set-Cookie
  main:
    web-application-type: reactive


server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
